### ISSUE TITLE
SyntaxError: invalid character in identifier

### ISSUE THREAD

**Issue by veka0** [markbookk/prntscrScraper#1]
sudo python code.py 10
  File "code.py", line 7
        sys.exit("\033[37mUsage: python " + sys.argv[0] + " (Number of threads)")
          ^
SyntaxError: invalid character in identifier

**Comment by akyj0e** [comment]
Как открыть?

**Comment by ahmedajaj** [comment]
use python 2 (2.7.15 in my case) instead of 3
подписчики овера даже до этого додуматься не могут)

**Comment by Ekali78** [comment]
> use python 2 (2.7.15 in my case) instead of 3
> подписчики овера даже до этого додуматься не могут)

Скачал эту версию открываю файл и ничего не происходит теперь нет ни ошибок и вообще ничего, подскажи что не так

**Comment by alekxeyuk** [comment]
Предлагаю вам использовать мою версию которая в 100 раз быстрее, на 3 питоне, с поддержкой прокси пулла. 
[https://github.com/alekxeyuk/Prnt.sc-Ultimate](https://github.com/alekxeyuk/Prnt.sc-Ultimate)

**Comment by Ekali78** [comment]
> Предлагаю вам использовать мою версию которая в 100 раз быстрее, на 3 питоне, с поддержкой прокси пулла.
> https://github.com/alekxeyuk/Prnt.sc-Ultimate

как установить proxybroker и beautifulsoup4-4.6.3 помоги разобраться

**Comment by veka0** [comment]
Pip install proxybroker
Pip install beautifulsoup4

**Comment by Ekali78** [comment]
> Pip install proxybroker
> Pip install beautifulsoup4

это в командной строке или в питоне ?

**Comment by veka0** [comment]
В командной строке...

**Comment by Ekali78** [comment]
> В командной строке...

все спс сам нашел решил проблему

**Comment by Ekali78** [comment]
> В командной строке...

твой скрипт запускать через IDLE ?

**Comment by veka0** [comment]
Какой скрипт?) Две отдельные команды для командной строки. Можно и догадаться.
